id: metan
display_name: めたん
main_color: "#d64aa0"
voicevox:
  speaker_id: 2
style:
  first_person: わたし
  endings: ["するわ", "ね", "かしら"]
  role: ツッコミ役
phrases:
  idea_intro: ["ここからは私、めたんが説明するわ"]
  explanation_start: ["要するにこういうことね"]
  conclusion: ["それで決まりね"]
