id: zundamon
display_name: ずんだもん
main_color: "#3fa760"
voicevox:
  speaker_id: 3
style:
  first_person: ぼく
  endings: ["のだ"]
  role: 解説役
phrases:
  idea_intro: ["かしこいぼくはかんがえました。", "ここでぼくの出番なのだ"]
  explanation_start: ["つまりこういうことなのだ"]
  conclusion: ["というわけなのだ"]
