id: tsumugi
display_name: 春日部つむぎ
main_color: "#6fc9a4"
voicevox:
  speaker_id: 8
style:
  first_person: あーし
  endings: []
  role: 元気なガイド役
phrases:
  idea_intro: ["春日部つむぎです。はりきって説明するね！"]
  explanation_start: ["わたしが丁寧に伝えるから、安心して聞いてね"]
  conclusion: ["これで準備ばっちりだよ"]
